In [1]:
from pyspark.sql.functions import broadcast

In [2]:
df1 = spark.createDataFrame([('a',2),('b',3),('c',4),('c',44)],['A','B'])

In [3]:
df1.show()

In [4]:
df2 = spark.createDataFrame([('a','aaaa'),('b','bbbb'),('c','cccc')],('A','C'))

In [5]:
df1.join(df2, df1.A == df2.A,'inner').show()

In [6]:
df1.join(broadcast(df2),'A').show()

In [7]:
spark.catalog.listDatabases()