In [1]:
titanic_data = spark.read.csv('/FileStore/tables/titanic_train-ac800.csv', header=True, inferSchema=True)

In [2]:
titanic_data.dtypes

In [3]:
df = spark.range(10)
df = df.withColumn("B",lit(5))
df2 = spark.range(10)

In [4]:
from pyspark.sql.functions import lit
df.withColumn('A', df2.id+1).count()

In [5]:
df2.id

In [6]:
df = spark.createDataFrame([(1, 4), (2, 5), (3, 6)], ["A", "B"])

In [7]:
df = df.withColumn('C',df.A + df.B)

In [8]:
df = df.select('*',(df.A > 2).alias("State"),(lit(2).alias("StateB")))

In [9]:
df.show()

In [10]:
import pyspark.sql.functions as F

In [11]:
df.select("*", F.when(df.C == 5,'Great').when(df.C == 7,'good').otherwise('Awesome').alias("result")).show()

In [12]:
titanic_data.createOrReplaceTempView('titanic')

In [13]:
display(spark.sql("select * from titanic where Sex='female'"))

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,null,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,null,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,null,C
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.55,C103,S
15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,null,S
16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0,null,S
19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31.0,1,0,345763,18.0,null,S
20,1,3,"Masselmani, Mrs. Fatima",female,null,0,0,2649,7.225,null,C
23,1,3,"""McGowan, Miss. Anna """"Annie""""""",female,15.0,0,0,330923,8.0292,null,Q
25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.075,null,S
26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38.0,1,5,347077,31.3875,null,S
29,1,3,"""O'Dwyer, Miss. Ellen """"Nellie""""""",female,null,0,0,330959,7.8792,null,Q
32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,null,1,0,PC 17569,146.5208,B78,C
33,1,3,"Glynn, Miss. Mary Agatha",female,null,0,0,335677,7.75,null,Q
39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0,null,S
40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,null,C
41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.475,null,S
42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27.0,1,0,11668,21.0,null,S
44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,null,C
45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,null,Q
48,1,3,"O'Driscoll, Miss. Bridget",female,null,0,0,14311,7.75,null,Q
50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8,null,S
53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29.0,1,0,2926,26.0,null,S
57,1,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5,null,S
59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.75,null,S
62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,null
67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.0,0,0,C.A. 29395,10.5,F33,S
69,1,3,"Andersson, Miss. Erna Alexandra",female,17.0,4,2,3101281,7.925,null,S
72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9,null,S
80,1,3,"Dowdell, Miss. Elizabeth",female,30.0,0,0,364516,12.475,null,S
83,1,3,"McDermott, Miss. Brigdet Delia",female,null,0,0,330932,7.7875,null,Q
85,1,2,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5,null,S
86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33.0,3,0,3101278,15.85,null,S
89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0,C23 C25 C27,S
99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0,null,S
101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,null,S
107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.65,null,S
110,1,3,"Moran, Miss. Bertha",female,null,1,0,371110,24.15,null,Q
112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,null,C
114,0,3,"Jussila, Miss. Katriina",female,20.0,1,0,4136,9.825,null,S
115,0,3,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,null,C
120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.275,null,S
124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13.0,E101,S
129,1,3,"Peter, Miss. Anna",female,null,1,1,2668,22.3583,F E69,C
133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5,null,S
134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.0,null,S
137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,null,0,2,2678,15.2458,null,C
142,1,3,"Nysten, Miss. Anna Sofia",female,22.0,0,0,347081,7.75,null,S
143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",female,24.0,1,0,STON/O2. 3101279,15.85,null,S
148,0,3,"""Ford, Miss. Robina Maggie """"Ruby""""""",female,9.0,2,2,W./C. 6608,34.375,null,S
152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6,C2,S
157,1,3,"""Gilnagh, Miss. Katherine """"Katie""""""",female,16.0,0,0,35851,7.7333,null,Q
162,1,2,"""Watt, Mrs. James (Elizabeth """"Bessie"""" Inglis Milne)""",female,40.0,0,0,C.A. 33595,15.75,null,S
167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,null,0,1,113505,55.0,E33,S
168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9,null,S
173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,11.1333,null,S
178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
181,0,3,"Sage, Miss. Constance Gladys",female,null,8,2,CA. 2343,69.55,null,S
185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.0,0,2,315153,22.025,null,S
187,1,3,"""O'Brien, Mrs. Thomas (Johanna """"Hannah"""" Godfrey)""",female,null,1,0,370365,15.5,null,Q
191,1,2,"Pinsky, Mrs. (Rosa)",female,32.0,0,0,234604,13.0,null,S
193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,350046,7.8542,null,S
195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C
196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
199,1,3,"""Madigan, Miss. Margaret """"Maggie""""""",female,null,0,0,370370,7.75,null,Q
200,0,2,"""Yrois, Miss. Henriette (""""Mrs Harbeck"""")""",female,24.0,0,0,248747,13.0,null,S
206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S
209,1,3,"""Carr, Miss. Helen """"Ellen""""""",female,16.0,0,0,367231,7.75,null,Q
212,1,2,"Cameron, Miss. Clear Annie",female,35.0,0,0,F.C.C. 13528,21.0,null,S
216,1,1,"Newell, Miss. Madeleine",female,31.0,1,0,35273,113.275,D36,C
217,1,3,"Honkanen, Miss. Eliina",female,27.0,0,0,STON/O2. 3101283,7.925,null,S
219,1,1,"Bazzani, Miss. Albina",female,32.0,0,0,11813,76.2917,D15,C
230,0,3,"Lefebre, Miss. Mathilde",female,null,3,1,4133,25.4667,null,S
231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.0,1,0,36973,83.475,C83,S
234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.0,4,2,347077,31.3875,null,S
236,0,3,"Harknett, Miss. Alice Phoebe",female,null,0,0,W./C. 6609,7.55,null,S
238,1,2,"""Collyer, Miss. Marjorie """"Lottie""""""",female,8.0,0,2,C.A. 31921,26.25,null,S
241,0,3,"Zabour, Miss. Thamine",female,null,1,0,2665,14.4542,null,C
242,1,3,"""Murphy, Miss. Katherine """"Kate""""""",female,null,1,0,367230,15.5,null,Q
247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25.0,0,0,347071,7.775,null,S
248,1,2,"Hamalainen, Mrs. William (Anna)",female,24.0,0,2,250649,14.5,null,S
252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0,1,1,347054,10.4625,G6,S
255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,null,S
256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,2650,15.2458,null,C
257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,null,0,0,PC 17585,79.2,null,C
258,1,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5,B77,S
259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,null,C
260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0,null,S
265,0,3,"Henry, Miss. Delia",female,null,0,0,382649,7.75,null,Q
269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
270,1,1,"Bissette, Miss. Amelia",female,35.0,0,0,PC 17760,135.6333,C99,S
273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.0,0,1,250644,19.5,null,S
275,1,3,"""Healy, Miss. Hanora """"Nora""""""",female,null,0,0,370375,7.75,null,Q
276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.0,0,0,347073,7.75,null,S
280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,null,S
290,1,3,"Connolly, Miss. Kate",female,22.0,0,0,370373,7.75,null,Q
291,1,1,"""Barber, Miss. Ellen """"Nellie""""""",female,26.0,0,0,19877,78.85,null,S
292,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0,1,0,11967,91.0792,B49,C
294,0,3,"Haas, Miss. Aloisia",female,24.0,0,0,349236,8.85,null,S
298,0,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.55,C22 C26,S
300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
301,1,3,"""Kelly, Miss. Anna Katherine """"Annie Kate""""""",female,null,0,0,9234,7.75,null,Q
304,1,2,"Keane, Miss. Nora A",female,null,0,0,226593,12.35,E101,Q
307,1,1,"Fleming, Miss. Margaret",female,null,0,0,17421,110.8833,null,C
308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)",female,17.0,1,0,PC 17758,108.9,C65,C
310,1,1,"Francatelli, Miss. Laura Mabel",female,30.0,0,0,PC 17485,56.9292,E36,C
311,1,1,"Hays, Miss. Margaret Bechstein",female,24.0,0,0,11767,83.1583,C54,C
312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.375,B57 B59 B63 B66,C
313,0,2,"Lahtinen, Mrs. William (Anna Sylfven)",female,26.0,1,1,250651,26.0,null,S
316,1,3,"Nilsson, Miss. Helmina Josefina",female,26.0,0,0,347470,7.8542,null,S
317,1,2,"Kantor, Mrs. Sinai (Miriam Sternin)",female,24.0,1,0,244367,26.0,null,S
319,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S
320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)",female,40.0,1,1,16966,134.5,E34,C
323,1,2,"Slayter, Miss. Hilda Mary",female,30.0,0,0,234818,12.35,null,Q
324,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)",female,22.0,1,1,248738,29.0,null,S
326,1,1,"Young, Miss. Marie Grice",female,36.0,0,0,PC 17760,135.6333,C32,C
328,1,2,"Ball, Mrs. (Ada E Hall)",female,36.0,0,0,28551,13.0,D,S
329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.525,null,S
330,1,1,"Hippach, Miss. Jean Gertrude",female,16.0,0,1,111361,57.9792,B18,C
331,1,3,"McCoy, Miss. Agnes",female,null,2,0,367226,23.25,null,Q
335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinsheimer)",female,null,1,0,PC 17611,133.65,null,S
338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5,E40,C
342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0,C23 C25 C27,S
346,1,2,"""Brown, Miss. Amelia """"Mildred""""""",female,24.0,0,0,248733,13.0,F33,S
347,1,2,"Smith, Miss. Marion Elsie",female,40.0,0,0,31418,13.0,null,S
348,1,3,"Davison, Mrs. Thomas Henry (Mary E Finck)",female,null,1,0,386525,16.1,null,S
357,1,1,"Bowerman, Miss. Elsie Edith",female,22.0,0,1,113505,55.0,E33,S
358,0,2,"Funk, Miss. Annie Clemmer",female,38.0,0,0,237671,13.0,null,S
359,1,3,"McGovern, Miss. Mary",female,null,0,0,330931,7.8792,null,Q
360,1,3,"""Mockler, Miss. Helen Mary """"Ellie""""""",female,null,0,0,330980,7.8792,null,Q
363,0,3,"Barbara, Mrs. (Catherine David)",female,45.0,0,1,2691,14.4542,null,C
367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.25,D37,C
368,1,3,"Moussa, Mrs. (Mantoura Boulos)",female,null,0,0,2626,7.2292,null,C
369,1,3,"Jermyn, Miss. Annie",female,null,0,0,14313,7.75,null,Q
370,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3,B35,C
375,0,3,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.075,null,S
376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,null,1,0,PC 17604,82.1708,null,C
377,1,3,"Landergren, Miss. Aurora Adelia",female,22.0,0,0,C 7077,7.25,null,S
381,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.525,null,C
382,1,3,"""Nakid, Miss. Maria (""""Mary"""")""",female,1.0,0,2,2653,15.7417,null,C
384,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline Towner)",female,35.0,1,0,113789,52.0,null,S
388,1,2,"Buss, Miss. Kate",female,36.0,0,0,27849,13.0,null,S
390,1,2,"Lehmann, Miss. Bertha",female,17.0,0,0,SC 1748,12.0,null,C
394,1,1,"Newell, Miss. Marjorie",female,23.0,1,0,35273,113.275,D36,C
395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)",female,24.0,0,2,PP 9549,16.7,G6,S
397,0,3,"Olsson, Miss. Elina",female,31.0,0,0,350407,7.8542,null,S
400,1,2,"Trout, Mrs. William H (Jessie L)",female,28.0,0,0,240929,12.65,null,S
403,0,3,"Jussila, Miss. Mari Aina",female,21.0,1,0,4137,9.825,null,S
405,0,3,"Oreskovic, Miss. Marija",female,20.0,0,0,315096,8.6625,null,S
410,0,3,"Lefebre, Miss. Ida",female,null,3,1,4133,25.4667,null,S
413,1,1,"Minahan, Miss. Daisy E",female,33.0,1,0,19928,90.0,C78,Q
416,0,3,"Meek, Mrs. Thomas (Annie Louise Rowley)",female,null,0,0,343095,8.05,null,S
417,1,2,"Drew, Mrs. James Vivian (Lulu Thorne Christian)",female,34.0,1,1,28220,32.5,null,S
418,1,2,"Silven, Miss. Lyyli Karoliina",female,18.0,0,2,250652,13.0,null,S
420,0,3,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.15,null,S
424,0,3,"Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)",female,28.0,1,1,347080,14.4,null,S
427,1,2,"Clarke, Mrs. Charles V (Ada Maria Winfield)",female,28.0,1,0,2003,26.0,null,S
428,1,2,"""Phillips, Miss. Kate Florence (""""Mrs Kate Louise Phillips Marshall"""")""",female,19.0,0,0,250655,26.0,null,S
432,1,3,"Thorneycroft, Mrs. Percival (Florence Kate White)",female,null,1,0,376564,16.1,null,S
433,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide Slow)",female,42.0,1,0,SC/AH 3085,26.0,null,S
436,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0,B96 B98,S
437,0,3,"""Ford, Miss. Doolina Margaret """"Daisy""""""",female,21.0,2,2,W./C. 6608,34.375,null,S
438,1,2,"Richards, Mrs. Sidney (Emily Hocking)",female,24.0,2,3,29106,18.75,null,S
441,1,2,"Hart, Mrs. Benjamin (Esther Ada Bloomfield)",female,45.0,1,1,F.C.C. 13529,26.25,null,S
444,1,2,"Reynaldo, Ms. Encarnacion",female,28.0,0,0,230434,13.0,null,S
447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.0,0,1,250644,19.5,null,S
449,1,3,"Baclini, Miss. Marie Catherine",female,5.0,2,1,2666,19.2583,null,C
458,1,1,"Kenyon, Mrs. Frederick R (Marion)",female,null,1,0,17464,51.8625,D21,S
459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5,null,S
470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,null,C
473,1,2,"West, Mrs. Edwy Arthur (Ada Mary Worth)",female,33.0,1,2,C.A. 34651,27.75,null,S
474,1,2,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",female,23.0,0,0,SC/AH Basle 541,13.7917,D,C
475,0,3,"Strandberg, Miss. Ida Sofia",female,22.0,0,0,7553,9.8375,null,S
480,1,3,"Hirvonen, Miss. Hildur E",female,2.0,0,1,3101298,12.2875,null,S
484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,null,S
486,0,3,"Lefebre, Miss. Jeannie",female,null,3,1,4133,25.4667,null,S
487,1,1,"Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)",female,35.0,1,0,19943,90.0,C93,S
497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C
499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.55,C22 C26,S
502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.75,null,Q
503,0,3,"O'Sullivan, Miss. Bridget Mary",female,null,0,0,330909,7.6292,null,Q
504,0,3,"Laitinen, Miss. Kristina Sofia",female,37.0,0,0,4135,9.5875,null,S
505,1,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.5,B79,S
507,1,2,"Quick, Mrs. Frederick Charles (Jane Richards)",female,33.0,0,2,26360,26.0,null,S
514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,1,0,PC 17603,59.4,null,C
517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.0,0,0,C.A. 34260,10.5,F33,S
519,1,2,"""Angle, Mrs. William A (Florence """"Mary"""" Agnes Hughes)""",female,36.0,1,0,226875,26.0,null,S
521,1,1,"Perreault, Miss. Anne",female,30.0,0,0,12749,93.5,B73,S
524,1,1,"Hippach, Mrs. Louis Albert (Ida Sophia Fischer)",female,44.0,0,1,111361,57.9792,B18,C
527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.5,null,S
531,1,2,"Quick, Miss. Phyllis May",female,2.0,1,1,26360,26.0,null,S
534,1,3,"Peter, Mrs. Catherine (Catherine Rizk)",female,null,0,2,2668,22.3583,null,C
535,0,3,"Cacic, Miss. Marija",female,30.0,0,0,315084,8.6625,null,S
536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.25,null,S
538,1,1,"LeRoy, Miss. Bertha",female,30.0,0,0,PC 17761,106.425,null,C
540,1,1,"Frolicher, Miss. Hedwig Margaritha",female,22.0,0,2,13568,49.5,B39,C
541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0,B22,S
542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.0,4,2,347082,31.275,null,S
543,0,3,"Andersson, Miss. Sigrid Elisabeth",female,11.0,4,2,347082,31.275,null,S
547,1,2,"Beane, Mrs. Edward (Ethel Clarke)",female,19.0,1,0,2908,26.0,null,S
555,1,3,"Ohman, Miss. Velin",female,22.0,0,0,347085,7.775,null,S
557,1,1,"""Duff Gordon, Lady. (Lucille Christiana Sutherland) (""""Mrs Morgan"""")""",female,48.0,1,0,11755,39.6,A16,C
559,1,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.65,E67,S
560,1,3,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",female,36.0,1,0,345572,17.4,null,S
565,0,3,"Meanwell, Miss. (Marion Ogden)",female,null,0,0,SOTON/O.Q. 392087,8.05,null,S
568,0,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,null,S
572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S
574,1,3,"Kelly, Miss. Mary",female,null,0,0,14312,7.75,null,Q
577,1,2,"Garside, Miss. Ethel",female,34.0,0,0,243880,13.0,null,S
578,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39.0,1,0,13507,55.9,E44,S
579,0,3,"Caram, Mrs. Joseph (Maria Elias)",female,null,1,0,2689,14.4583,null,C
581,1,2,"Christy, Miss. Julie Rachel",female,25.0,1,1,237789,30.0,null,S
582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth Morris)",female,39.0,1,1,17421,110.8833,C68,C
586,1,1,"Taussig, Miss. Ruth",female,18.0,0,2,110413,79.65,E68,S
592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C
594,0,3,"Bourke, Miss. Mary",female,null,0,2,364848,7.75,null,Q
597,1,2,"Leitch, Miss. Jessie Wills",female,null,0,0,248727,33.0,null,S
601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)",female,24.0,2,1,243847,27.0,null,S
609,1,2,"Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)",female,22.0,1,2,SC/Paris 2123,41.5792,null,C
610,1,1,"Shutes, Miss. Elizabeth W",female,40.0,0,0,PC 17582,153.4625,C125,S
611,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)",female,39.0,1,5,347082,31.275,null,S
613,1,3,"Murphy, Miss. Margaret Jane",female,null,1,0,367230,15.5,null,Q
616,1,2,"Herman, Miss. Alice",female,24.0,1,2,220845,65.0,null,S
618,0,3,"Lobb, Mrs. William Arthur (Cordelia K Stanlick)",female,26.0,1,0,A/5. 3336,16.1,null,S
619,1,2,"Becker, Miss. Marion Louise",female,4.0,2,1,230136,39.0,F4,S
628,1,1,"Longley, Miss. Gretchen Fiske",female,21.0,0,0,13502,77.9583,D9,S
635,0,3,"Skoog, Miss. Mabel",female,9.0,3,2,347088,27.9,null,S
636,1,2,"Davis, Miss. Mary",female,28.0,0,0,237668,13.0,null,S
639,0,3,"Panula, Mrs. Juha (Maria Emilia Ojala)",female,41.0,0,5,3101295,39.6875,null,S
642,1,1,"Sagesser, Mlle. Emma",female,24.0,0,0,PC 17477,69.3,B35,C
643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.0,3,2,347088,27.9,null,S
645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,null,C
650,1,3,"Stanley, Miss. Amy Zillah Elsie",female,23.0,0,0,CA. 2314,7.55,null,S
652,1,2,"Doling, Miss. Elsie",female,18.0,0,1,231919,23.0,null,S
654,1,3,"""O'Leary, Miss. Hanora """"Norah""""""",female,null,0,0,330919,7.8292,null,Q
655,0,3,"""Hegarty, Miss. Hanora """"Nora""""""",female,18.0,0,0,365226,6.75,null,Q
658,0,3,"Bourke, Mrs. John (Catherine)",female,32.0,1,1,364849,15.5,null,Q
670,1,1,"Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)",female,null,1,0,19996,52.0,C126,S
671,1,2,"Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)",female,40.0,1,1,29750,39.0,null,S
678,1,3,"Turja, Miss. Anna Sofia",female,18.0,0,0,4138,9.8417,null,S

In [14]:
spark.catalog.listTables()

In [15]:
spark.catalog.dropTempView('titanic')

In [16]:
titanic_data.createOrReplaceGlobalTempView('titanic_global')

In [17]:
spark.catalog.dropGlobalTempView('titanic_globalspar')

In [18]:
spark.sql("select * from global_titanic_global")

In [19]:
stringCSVRDD = sc.parallelize([(123, 'Katie', 19, 'brown'), (234, 'Michael', 22, 'green'), (345, 'Simone', 22, 11)])

from pyspark.sql.types import StringType, StructField, LongType, StructType

In [20]:
schema = StructType([
    StructField("id", LongType(), True),    
    StructField("name", StringType(), True),
    StructField("age", LongType(), True),
    StructField("eyeColor", StringType(), True)
])

In [21]:
df = spark.createDataFrame(stringCSVRDD, schema)

In [22]:
df[df.id == 345].count()

In [23]:
from pyspark.sql.types import Row

In [24]:
# Create the Departments
department1 = Row(id='123456', name='Computer Science')
department2 = Row(id='789012', name='Mechanical Engineering')
department3 = Row(id='345678', name='Theater and Drama')
department4 = Row(id='901234', name='Indoor Recreation')

In [25]:
Employee = Row("firstName", "lastName", "email", "salary")

In [26]:
employee1 = Employee('michael', 'armbrust', 'no-reply@berkeley.edu', 100000)
employee11 = Employee('michael', 'armbrust', 'no-reply@berkeley.edu', 200000)
employee2 = Employee('xiangrui', 'meng', 'no-reply@stanford.edu', 120000)
employee3 = Employee('matei', None, 'no-reply@waterloo.edu', 140000)
employee31 = Employee('matei', None, 'no-reply@waterloo.edu', 180000)
employee4 = Employee(None, 'wendell', 'no-reply@berkeley.edu', 160000)

In [27]:
departmentWithEmployees1 = Row(department=department1, employees=[employee1, employee2])
departmentWithEmployees2 = Row(department=department2, employees=[employee3, employee4, employee11])
departmentWithEmployees3 = Row(department=department3, employees=[employee1, employee4, employee31])
departmentWithEmployees4 = Row(department=department4, employees=[employee2, employee3])

In [28]:
df = spark.createDataFrame([departmentWithEmployees1,departmentWithEmployees2,departmentWithEmployees3,departmentWithEmployees4])

In [29]:
df.write.json('emp.csv')

In [30]:
display(df)

department,employees
"List(123456, Computer Science)","List(List(michael, armbrust, no-reply@berkeley.edu, 100000), List(xiangrui, meng, no-reply@stanford.edu, 120000))"
"List(789012, Mechanical Engineering)","List(List(matei, null, no-reply@waterloo.edu, 140000), List(null, wendell, no-reply@berkeley.edu, 160000), List(michael, armbrust, no-reply@berkeley.edu, 200000))"
"List(345678, Theater and Drama)","List(List(michael, armbrust, no-reply@berkeley.edu, 100000), List(null, wendell, no-reply@berkeley.edu, 160000), List(matei, null, no-reply@waterloo.edu, 180000))"
"List(901234, Indoor Recreation)","List(List(xiangrui, meng, no-reply@stanford.edu, 120000), List(matei, null, no-reply@waterloo.edu, 140000))"

In [31]:
from pyspark.sql.functions import explode
df = df.select("*",explode("employees").alias("e"))
df = df[['department','e']]

In [32]:
display(df)

department,e
"List(123456, Computer Science)","List(michael, armbrust, no-reply@berkeley.edu, 100000)"
"List(123456, Computer Science)","List(xiangrui, meng, no-reply@stanford.edu, 120000)"
"List(789012, Mechanical Engineering)","List(matei, null, no-reply@waterloo.edu, 140000)"
"List(789012, Mechanical Engineering)","List(null, wendell, no-reply@berkeley.edu, 160000)"
"List(789012, Mechanical Engineering)","List(michael, armbrust, no-reply@berkeley.edu, 200000)"
"List(345678, Theater and Drama)","List(michael, armbrust, no-reply@berkeley.edu, 100000)"
"List(345678, Theater and Drama)","List(null, wendell, no-reply@berkeley.edu, 160000)"
"List(345678, Theater and Drama)","List(matei, null, no-reply@waterloo.edu, 180000)"
"List(901234, Indoor Recreation)","List(xiangrui, meng, no-reply@stanford.edu, 120000)"
"List(901234, Indoor Recreation)","List(matei, null, no-reply@waterloo.edu, 140000)"

In [33]:
df.selectExpr("department.*","e.*").show()

In [34]:
from pyspark.sql.types import *
from pyspark.sql.functions import col, count, rand, collect_list, explode, struct, count, lit
from pyspark.sql.functions import pandas_udf, PandasUDFType, udf

In [35]:
df = spark.range(0, 10 * 1000 * 1000).withColumn('id', (col('id') / 10000).cast('integer')).withColumn('v', rand())
df.cache()
df.count()

In [37]:
from pyspark.sql.types import IntegerType
addone = udf(lambda s: col(s) + 1, IntegerType())

In [38]:
df.withColumn('n',addone(df.v)).count()

In [39]:
@udf('double')
def plus_one(v):
    return v + 1

%timeit df.withColumn('v', plus_one(df.v)).agg(count(col('v'))).show()

In [40]:
@pandas_udf("double", PandasUDFType.SCALAR)
def pandas_plus_one(v):
  print (len(v),type(v))
  return v + 1

#%timeit df.repartition(8).withColumn('v', pandas_plus_one(df.v)).agg(count(col('v'))).show()

In [41]:
df.rdd.getNumPartitions()

In [42]:
df.repartition(8).withColumn('v', pandas_plus_one(df.v)).agg(count(col('v'))).show()

In [43]:
@pandas_udf(df.schema, PandasUDFType.GROUPED_MAP)
# Input/output are both a pandas.DataFrame
def pandas_subtract_mean(pdf):
  print (len(pdf),type(pdf))
  print (pdf.id.unique())
  return pdf.assign(v=pdf.v - pdf.v.mean())

df.groupby('id').apply(pandas_subtract_mean).agg(count(col('v'))).show()

In [44]:
help(df.groupBy)

In [45]:
\